
[tools]
bat = "latest"
delta = "latest"
eza = "latest"
fzf = "latest"
go = "1.24.5"
"go:github.com/nametake/golangci-lint-langserver" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:mvdan.cc/gofumpt" = "latest"
"go:github.com/jesseduffield/lazydocker" = "latest"
golangci-lint = "latest"
lazygit = "latest"
lua-language-server = "latest"
mysql = "latest"
node = "latest"
"npm:@biomejs/biome" = "latest"
"npm:@vue/language-server" = "latest"
"npm:eslint" = "latest"
"npm:prettier" = "latest"
"npm:tailwindcss-language-server" = "latest"
"npm:vls" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:vue-language-server" = "latest"
"npm:yarn" = "latest"
ripgrep = "latest"
starship = "latest"
zoxide = "latest"
terraform = "latest"
terraform-ls = "latest"
awscli = "latest"
terraformer = "latest"
"npm:claude" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
codex = "latest"
"npm:@vtsls/language-server" = "latest"
gh = "latest"
gemini-cli = "latest"
saml2aws = "latest"
yazi = "latest"
"npm:runme" = "latest"
xc = "latest"

[settings]
experimental = true

